@startuml

Editor ->> Lspc: Notify
Lspc -> LangServerHandler: Notify/Request
LangServerHandler ->> RpcClient: Notify/Request
...
RpcClient ->> Lspc: Notify/Response
Lspc -> LangServerHandler: Notify/Response
LangServerHandler ->> Lspc: Update editor
Lspc -> Editor: Update
Editor --> Lspc: Response

@enduml
