@startuml

Editor ->> Lspc: Notify
Lspc -> LspChannel: Notify/Request
LspChannel ->> RpcClient: Notify/Request
...
RpcClient ->> Lspc: Notify/Response
Lspc -> LspChannel: Notify/Response
LspChannel ->> Lspc: Update editor
Lspc -> Editor: Update
Editor --> Lspc: Response

@enduml
