@startuml

Editor ->> "Main Loop": Notify
"Main Loop" -> LSPHandler: Notify/Request
LSPHandler ->> RpcClient: Notify/Request
...
RpcClient ->> "Main Loop": Notify/Response
"Main Loop" -> LSPHandler: Notify/Response
LSPHandler ->> "Main Loop": Update editor
"Main Loop" -> Editor: Update
Editor --> "Main Loop": Response

@enduml
